PIP-2.md English Translation
PlatONnetwork/PIPs pull request #34
Opened 2021-06-21 03:58 UTC by xiyu1984

PIP-2.md English Translation

2021-06-24 06:55 UTC, benbaley requested changes
please rename the filename to PIP-2-EN.md

2021-06-24 06:55 UTC, benbaley commented on PIPs/PIP-2.md
> +From these differences, Platon can be made compatible with Ethereum with minimal changes.
Platon should be PlatON

2021-06-25 05:49 UTC, biganxin commented
> please rename the filename to PIP-2-EN.md
This English translation is recommended without adding a new document
Just add the English translation to the original Chinese document

2021-06-25 06:08 UTC, benbaley approved these changes
LGTM

2021-06-25 06:08 UTC, merged